name: Rerun PR Checks

on:
  repository_dispatch:
    types:
      - rerun-pr-check

jobs:
  rerun-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Fetch Open PRs Targeting the Branch
        id: fetch-prs
        run: |
          TARGET_BRANCH="${{ github.event.client_payload.branch }}"
          PRS=$(gh pr list --json number,baseRef --jq ".[] | select(.baseRef == \"${TARGET_BRANCH}\") | .number")
          echo "PRs targeting branch '${TARGET_BRANCH}': $PRS"
          echo "pr_numbers=$PRS" >> $GITHUB_ENV

      - name: Rerun Workflow Check on PRs
        if: env.pr_numbers
        run: |
          for pr in $PR_NUMBERS; do
            echo "Rerunning workflow for PR #$pr"
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/lironm16/android/actions/runs/<workflow-id>/rerun
          done
